Pass1-345: erase external flash after signing
Foundation-Devices/passport2 pull request #79
Opened 2023-01-02 19:51 UTC by mjg-foundation

2023-01-05 03:40 UTC, mjg-foundation commented
@FoundationKen what do you think about getting this ino 2.0.5 for testing?

2023-01-05 20:37 UTC, mjg-foundation commented
@FoundationKen did you have a comment on this somewhere else in linear/twist? I remember reading it but can't find it now.

2023-01-24 16:25 UTC, jeandudey requested changes
LGTM, just the nit pick about the copy on the spinner task.

Tested and works correctly.

2023-01-24 16:25 UTC, jeandudey commented on ports/stm32/boards/Passport/modules/utils.py
> +    await spinner_task('Clearing transaction from flash', clear_psbt_from_external_flash_task)
I'm not sure we should indicate that we are clearing the PSBT from the flash, maybe a "Cleaning" or variations.

2023-01-24 23:34 UTC, FoundationKen commented on ports/stm32/boards/Passport/modules/tasks/copy_psbt_file_to_external_flash_task.py
> +                await on_done(0, None, Error.PSBT_INVALID)
We should differentiate between invalid PSBTs and ones that are just too long for us.  Add another error like `Error.PSBT_TOO_LARGE` and then show a different error in the code that calls this task.

2023-01-24 23:34 UTC, FoundationKen commented on ports/stm32/boards/Passport/modules/tasks/copy_psbt_to_external_flash_task.py
> +        if psbt_len > MAX_TXN_LEN:
Same comment as above for `Error.PSBT_TOO_LARGE`.

2023-02-06 22:48 UTC, FoundationKen approved these changes

2023-02-06 22:48 UTC, FoundationKen approved these changes

2023-02-06 22:52 UTC, merged