Pass1-24: bip85
Foundation-Devices/passport2 pull request #94
Opened 2023-01-17 07:29 UTC by mjg-foundation

I made a basic UI and implentation for BIP 85, where it is treated as an extension, and the only functionality is generating and displaying a 24 word seed and a QR of the raw seed.

2023-01-24 16:35 UTC, jeandudey requested changes

2023-01-24 16:35 UTC, jeandudey commented on ports/stm32/boards/Passport/modules/flows/view_seed_words_flow.py
> +            (words, passphrase, error) = await spinner_task('Retrieving Seed', get_seed_words_task)
This can be the same copy-writing for both I think. (Retrieving Seed).

2023-01-24 16:35 UTC, jeandudey commented on ports/stm32/boards/Passport/modules/ui/ui.py
> +            if common.settings.get('ext.bip85.enabled', False):
This setting should be added to the `Extensions` menu :eyes:

2023-03-12 14:17 UTC, jeandudey commented on ports/stm32/boards/Passport/modules/tasks/get_seed_words_task.py
> +        await one_done(None, '{}'.format(e))
```suggestion
        await on_done(None, '{}'.format(e))
```

2023-03-30 17:17 UTC, FoundationKen commented on ports/stm32/boards/Passport/modules/wallets/utils.py
> +# Dynamic find the next bip85 number rather than storing it - we never want to skip an account number
Dynamically

2023-04-02 06:01 UTC, FoundationKen approved these changes

2023-04-02 07:21 UTC, merged